function R = MD_dirrnd(alpha,N)
% _
% Dirichlet-distributed random numbers
% FORMAT R = MD_dirrnd(alpha,N)
% 
%     alpha - a  1 x K vector with parameters of the distribution
%     N     - an integer specifying the number of samples to be drawn
% 
%     R     - an N x K matrix with Dirichlet-distributed random numbers
% 
% FORMAT R = MD_dirrnd(alpha,N) returns N samples from the Dirichlet
% distribution with parameters alpha. Random numbers are generated by
% exploiting the fact that Dirichlet random variables are normalized
% standard Gamma variates [1].
% 
% References:
% [1] Gelman A, Carlin JB, Stern HS, Dunson DB, Vehtari A, Rubin DB (2013):
%     "Bayesian Data Analysis". Chapman & Hall, 3rd edition, p. 583.
% 
% Author: Joram Soch, BCCN Berlin
% E-Mail: joram.soch@bccn-berlin.de
% 
% First edit: 21/10/2014, 18:30 (V0.2/V6)
%  Last edit: 12/11/2015, 11:00 (V0.3/V11)


% Get dimensionality
%-------------------------------------------------------------------------%
K = numel(alpha);

% Generate Gamma random numbers
%-------------------------------------------------------------------------%
R = gamrnd(repmat(alpha,[N 1]),1); % MD_gamrnd(...) / spm_gamrnd(...)

% calculate Dirichlet random numbers
%-------------------------------------------------------------------------%
R = R./repmat(sum(R,2),[1 K]);